import "package:dart_web_test/solid.dart";
import "package:dart_web_test/solid_dom.dart";
import "package:web/web.dart" as web;

import "./examples/dialog_basic.dart";
import "./examples/overlay_basic.dart";
import "./examples/focus_scope_basic.dart";
import "./examples/interact_outside_basic.dart";
import "./examples/popper_basic.dart";
import "./examples/selection_core_basic.dart";
import "./examples/popover_basic.dart";
import "./examples/tooltip_basic.dart";
import "./examples/dropdown_menu_basic.dart";
import "./examples/menubar_basic.dart";
import "./examples/context_menu_basic.dart";
import "./examples/toast_basic.dart";
import "./examples/select_basic.dart";
import "./examples/combobox_basic.dart";
import "./examples/listbox_basic.dart";
import "./examples/checkbox_basic.dart";
import "./examples/tabs_basic.dart";
import "./examples/accordion_basic.dart";
import "./examples/switch_basic.dart";
import "./examples/runtime_reactivity_basic.dart";
import "./examples/runtime_ownership_basic.dart";
import "./examples/runtime_dom_basic.dart";
import "./examples/runtime_resources_basic.dart";
import "./examples/runtime_context_basic.dart";
import "./examples/button_basic.dart";
import "./examples/badge_basic.dart";
import "./examples/radio_group_basic.dart";
import "./examples/separator_basic.dart";
import "./examples/toggle_group_basic.dart";
import "./examples/progress_basic.dart";
import "./examples/spinner_basic.dart";
import "./examples/avatar_basic.dart";
import "./examples/breadcrumbs_basic.dart";
import "./examples/alert_basic.dart";
import "./examples/navigation_menu_basic.dart";
import "./examples/input_basic.dart";
import "./examples/label_basic.dart";
import "./examples/form_field_basic.dart";
import "./examples/textarea_basic.dart";
import "./examples/fieldset_basic.dart";

typedef DocsDemoMount = Dispose Function(web.Element mount);

final Map<String, DocsDemoMount> docsDemos = {
  "button-basic": mountDocsButtonBasic,
  "badge-basic": mountDocsBadgeBasic,
  "avatar-basic": mountDocsAvatarBasic,
  "alert-basic": mountDocsAlertBasic,
  "input-basic": mountDocsInputBasic,
  "label-basic": mountDocsLabelBasic,
  "form-field-basic": mountDocsFormFieldBasic,
  "textarea-basic": mountDocsTextareaBasic,
  "fieldset-basic": mountDocsFieldsetBasic,
  "checkbox-basic": mountDocsCheckboxBasic,
  "spinner-basic": mountDocsSpinnerBasic,
  "radio-group-basic": mountDocsRadioGroupBasic,
  "separator-basic": mountDocsSeparatorBasic,
  "toggle-group-basic": mountDocsToggleGroupBasic,
  "progress-basic": mountDocsProgressBasic,
  "breadcrumbs-basic": mountDocsBreadcrumbsBasic,
  "navigation-menu-basic": mountDocsNavigationMenuBasic,
  "dialog-basic": mountDocsDialogBasic,
  "overlay-basic": mountDocsOverlayBasic,
  "focus-scope-basic": mountDocsFocusScopeBasic,
  "interact-outside-basic": mountDocsInteractOutsideBasic,
  "popper-basic": mountDocsPopperBasic,
  "selection-core-basic": mountDocsSelectionCoreBasic,
  "popover-basic": mountDocsPopoverBasic,
  "tooltip-basic": mountDocsTooltipBasic,
  "dropdown-menu-basic": mountDocsDropdownMenuBasic,
  "menubar-basic": mountDocsMenubarBasic,
  "context-menu-basic": mountDocsContextMenuBasic,
  "toast-basic": mountDocsToastBasic,
  "select-basic": mountDocsSelectBasic,
  "combobox-basic": mountDocsComboboxBasic,
  "listbox-basic": mountDocsListboxBasic,
  "tabs-basic": mountDocsTabsBasic,
  "accordion-basic": mountDocsAccordionBasic,
  "switch-basic": mountDocsSwitchBasic,
  "runtime-reactivity-basic": mountDocsRuntimeReactivityBasic,
  "runtime-ownership-basic": mountDocsRuntimeOwnershipBasic,
  "runtime-dom-basic": mountDocsRuntimeDomBasic,
  "runtime-resources-basic": mountDocsRuntimeResourcesBasic,
  "runtime-context-basic": mountDocsRuntimeContextBasic,
};
