import "package:web/web.dart" as web;

import "../solid_dom/core/combobox.dart";

/// Styled Combobox (Solidus UI skin).
///
/// For an unstyled primitive, use `createCombobox` from `solid_dom`.
web.DocumentFragment Combobox<T>({
  required bool Function() open,
  required void Function(bool next) setOpen,
  required web.HTMLElement anchor,
  required web.HTMLInputElement input,
  web.HTMLButtonElement? triggerButton,
  required Iterable<ComboboxOption<T>> Function() options,
  required T? Function() value,
  required void Function(T? next) setValue,
  bool Function(T a, T b)? equals,
  String? listboxId,
  String placement = "bottom-start",
  double offset = 6,
  double viewportPadding = 8,
  bool flip = true,
  bool showArrow = false,
  double arrowPadding = 4,
  bool allowsEmptyCollection = false,
  bool keepOpenOnEmpty = false,
  String emptyText = "No results.",
  bool noResetInputOnBlur = false,
  bool disallowEmptySelection = false,
  bool closeOnSelection = true,
  ComboboxFilter<T>? filter,
  String triggerMode = "input",
  void Function(String reason)? onClose,
  int exitMs = 0,
  String? portalId,
  ComboboxOptionBuilder<T>? optionBuilder,
}) {
  return createCombobox(
    open: open,
    setOpen: setOpen,
    anchor: anchor,
    input: input,
    triggerButton: triggerButton,
    options: options,
    value: value,
    setValue: setValue,
    equals: equals,
    listboxId: listboxId,
    placement: placement,
    offset: offset,
    viewportPadding: viewportPadding,
    flip: flip,
    showArrow: showArrow,
    arrowPadding: arrowPadding,
    allowsEmptyCollection: allowsEmptyCollection,
    keepOpenOnEmpty: keepOpenOnEmpty,
    emptyText: emptyText,
    noResetInputOnBlur: noResetInputOnBlur,
    disallowEmptySelection: disallowEmptySelection,
    closeOnSelection: closeOnSelection,
    filter: filter,
    triggerMode: triggerMode,
    onClose: onClose,
    exitMs: exitMs,
    portalId: portalId,
    listboxClassName: "card listbox",
    listboxScrollClassName: "listboxScroll",
    listboxOptionClassName: "listboxOption",
    listboxSectionGroupClassName: "listboxGroup",
    listboxSectionLabelClassName: "listboxGroupLabel",
    listboxEmptyClassName: "listboxEmpty",
    optionBuilder: optionBuilder,
  );
}
