#!/usr/bin/env bash
set -euo pipefail

CHANNEL_DEFAULT="stable"
VERSION_DEFAULT="3.10.7"

CHANNEL="${DART_SDK_CHANNEL:-$CHANNEL_DEFAULT}"
VERSION="${DART_SDK_VERSION:-$VERSION_DEFAULT}"

OS_RAW="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH_RAW="$(uname -m | tr '[:upper:]' '[:lower:]')"

case "$OS_RAW" in
  linux*) OS="linux" ;;
  darwin*) OS="macos" ;;
  *)
    echo "Error: unsupported OS '$OS_RAW' (expected Linux or Darwin)." >&2
    exit 1
    ;;
esac

case "$ARCH_RAW" in
  x86_64|amd64) ARCH="x64" ;;
  arm64|aarch64) ARCH="arm64" ;;
  *)
    echo "Error: unsupported arch '$ARCH_RAW' (expected x86_64/arm64)." >&2
    exit 1
    ;;
esac

URL_DEFAULT="https://storage.googleapis.com/dart-archive/channels/$CHANNEL/release/$VERSION/sdk/dartsdk-$OS-$ARCH-release.zip"
URL="${1:-$URL_DEFAULT}"

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALL_DIR="${DART_SDK_DIR:-"$ROOT_DIR/.dart-sdk"}"
SDK_DIR="$INSTALL_DIR/dart-sdk"
DART_BIN="$SDK_DIR/bin/dart"
ENV_LOCAL="$ROOT_DIR/.env.local"

CACHE_DIR="$ROOT_DIR/.cache"
ZIP_PATH="$CACHE_DIR/dartsdk-$OS-$ARCH-release.zip"

mkdir -p "$INSTALL_DIR" "$CACHE_DIR"

if [[ -x "$DART_BIN" ]]; then
  echo "Dart already provisioned at: $DART_BIN"
  "$DART_BIN" --version || true
  exit 0
fi

if ! command -v unzip >/dev/null 2>&1; then
  echo "Error: 'unzip' is required but not found on PATH." >&2
  exit 1
fi

echo "Downloading Dart SDK zip..."
if command -v curl >/dev/null 2>&1; then
  curl -fsSL --retry 3 --retry-delay 1 -o "$ZIP_PATH" "$URL"
elif command -v wget >/dev/null 2>&1; then
  wget -qO "$ZIP_PATH" "$URL"
else
  echo "Error: need either 'curl' or 'wget' to download $URL" >&2
  exit 1
fi

TMP_DIR="$(mktemp -d)"
cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

echo "Extracting to $INSTALL_DIR..."
unzip -q "$ZIP_PATH" -d "$TMP_DIR"

if [[ ! -d "$TMP_DIR/dart-sdk" ]]; then
  echo "Error: unexpected zip layout; expected 'dart-sdk/' folder." >&2
  exit 1
fi

rm -rf "$SDK_DIR"
mkdir -p "$INSTALL_DIR"
mv "$TMP_DIR/dart-sdk" "$SDK_DIR"

echo "Provisioned Dart:"
"$DART_BIN" --version

if [[ ! -f "$ENV_LOCAL" ]]; then
  cat >"$ENV_LOCAL" <<EOF
# Auto-generated by scripts/provision-dart.sh
DART=$DART_BIN
EOF
  echo "Wrote $ENV_LOCAL"
fi

echo "Tip: run with DART=\"$DART_BIN\" (or add \"$SDK_DIR/bin\" to PATH)."
